### ISSUE TITLE
ankiweb version of AJT Japanese cannot generate fields

### ISSUE THREAD

**Issue by hduongd** [Ajatt-Tools/Japanese#16]
On the latest version of Anki (24.06.3) and using the latest version of the add-on retrieved from AnkiWeb, the addon fails to generate furigana fields, search for audio, etc. Using Arch Linux 6.9.7-arch-1-1.

Steps to reproduce:

1. Create a flashcard (I am using the "Japanese sentences" template)
2. Fill the "VocabKanji" field with a word
3. Upon attempting to generate furigana (Alt+;), etc., the add-on will stop working.

Log:
```
Anki 24.06.3 (a5c90890) (src) (ao)
Python 3.12.4 Qt 6.7.2 PyQt 6.7.0
Platform: Linux-6.9.7-arch1-1-x86_64-with-glibc2.39

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/aqt/webview.py", line 637, in handler
    cb(val)
  File "/usr/lib/python3.12/site-packages/aqt/editor.py", line 634, in <lambda>
    self.web.evalWithCallback("saveNow(%d)" % keepFocus, lambda res: callback())
                                                                     ^^^^^^^^^^
  File "/home/.../.local/share/Anki2/addons21/1344485230/editor_toolbar.py", line 80, in decorator
    func(editor)
  File "/home/.../.local/share/Anki2/addons21/1344485230/editor_toolbar.py", line 155, in <lambda>
    ).run()
      ^^^^^
  File "/home/.../.local/share/Anki2/addons21/1344485230/tasks.py", line 170, in run
    changed = self._do_task(task, aud_mgr=session) or changed
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../.local/share/Anki2/addons21/1344485230/tasks.py", line 185, in _do_task
    ).run(
      ^^^^
  File "/home/.../.local/share/Anki2/addons21/1344485230/tasks.py", line 69, in run
    out_text = self._generate_text(src_text)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../.local/share/Anki2/addons21/1344485230/tasks.py", line 96, in _generate_text
    search_results = self._aud_src_mgr.search_audio(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../.local/share/Anki2/addons21/1344485230/audio.py", line 138, in search_audio
    hits[src_text].extend(self._search_word_variants(src_text))
  File "/home/.../.local/share/Anki2/addons21/1344485230/audio.py", line 197, in _search_word_variants
    yield from self.search_word(src_text)
  File "/home/.../.local/share/Anki2/addons21/1344485230/audio_manager/source_manager.py", line 136, in search_word
    yield self._resolve_file(self._audio_sources[file.source_name], file)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../.local/share/Anki2/addons21/1344485230/audio_manager/source_manager.py", line 176, in _resolve_file
    url=source.join(source.media_dir, file.file_name),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../.local/share/Anki2/addons21/1344485230/audio_manager/audio_source.py", line 61, in join
    return "/".join(*args)
           ^^^^^^^^^^^^^^^
TypeError: str.join() takes exactly one argument (2 given)

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AJT Japanese ['1344485230', 2024-07-01T19:45, 'None', '']

===IDs of active AnkiWeb add-ons===
1344485230

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AJT Card Management ['1021636467', 2024-03-15T20:51, 'None', '']
AJT Flexible Grading ['1715096333', 2024-06-08T12:08, 'None', '']
AJT Media Converter ['1151815987', 2024-06-29T06:15, 'None', mod]
Advanced Browser ['874215009', 2023-10-21T09:34, 'None', '']
AnkiConnect ['2055492159', 2024-06-17T21:37, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T20:43, 'None', '']
True Retention ['613684242', 2017-11-19T14:43, 'None', '']
```

As the log shows above I have disabled all other add-ons. It appears the problem occurs because 'args' is being unwrapped into join() on line 61 of `audio_manager/audio_source.py`. This issue appears to be resolved if the line is replaced with `return "/".join(args)`.

**Comment by tatsumoto-ren** [comment]
Thanks for the report. Should be fixed now.
