### ISSUE TITLE
Add-on Startup Failed -  AJT Japanese Furigana Pitch Accent Native pronunciations⁩

### ISSUE THREAD

**Issue by hisamigame** [Ajatt-Tools/Japanese#19]
Upon updating the "AJT Japanese Furigana Pitch Accent Native pronunciations"⁩ add-on today, I get a message titled 'Add-on Startup Failed' whenever I start Anki.

OS: Linux Mint 21.3
Anki version: 24.11 (87ccd24e)⁩
(Python 3.9.18 Qt 6.6.2 PyQt 6.6.1)

**Comment by tatsumoto-ren** [comment]
Please ask on https://tatsumoto.neocities.org/blog/join-our-community.html instead. It is easier for our members to provide support over in the chats. Thank you!

**Comment by hisamigame** [comment]
I'm sorry, I don't want to use Telegram.

I found the relevant error message.
```
When loading AJT Japanese  Furigana Pitch Accent Native pronunciations:
Traceback (most recent call last):
  File "aqt.addons", line 250, in loadAddons
  File "/home/me/.local/share/Anki2/addons21/1344485230/__init__.py", line 36, in <module>
    start_addon()
  File "/home/me/.local/share/Anki2/addons21/1344485230/__init__.py", line 10, in start_addon
    from . import (
  File "/home/me/.local/share/Anki2/addons21/1344485230/gui.py", line 20, in <module>
    from .ajt_common.enum_select_combo import EnumSelectCombo
  File "/home/me/.local/share/Anki2/addons21/1344485230/ajt_common/enum_select_combo.py", line 12, in <module>
    class EnumSelectCombo(QComboBox):
  File "/home/me/.local/share/Anki2/addons21/1344485230/ajt_common/enum_select_combo.py", line 15, in EnumSelectCombo
    enum_type: Optional[enum.EnumType] = None,
AttributeError: module 'enum' has no attribute 'EnumType'
```
Looks like EnumType is not part of the enum library for python 3.10:
https://docs.python.org/3.10/library/enum.html

**Comment by hisamigame** [comment]
Update. I managed to fix it. Here is how:
In `~/.local/share/Anki2/addons21/1344485230/ajt_common/enum_select_combo.py`
Replace the two instances of `enum.EnumType` with `enum.EnumMeta`. Your `__init__` method should look like:
```
    def __init__(
        self,
        enum_type: enum.EnumMeta = None,
        initial_value: Union[enum.Enum, str, None] = None,
        show_values: bool = False,
        parent=None,
    ) -> None:
        super().__init__(parent)
        if enum_type is None:
            assert isinstance(initial_value, enum.Enum)
            enum_type = type(initial_value)
        assert isinstance(enum_type, enum.EnumMeta)
        for item in enum_type:
            self.addItem(ui_translate(item.value if show_values else item.name), item)
        if initial_value is not None:
            self.setCurrentName(initial_value)
```

**Comment by tatsumoto-ren** [comment]
Apparently, the python 3.9 version of anki doesn't work with the latest update.

**Comment by tatsumoto-ren** [comment]
Thank you for the bug report. The fix has been uploaded.
