### ISSUE TITLE
Crash after updating addon

### ISSUE THREAD

**Issue by AommyPatty** [Ajatt-Tools/Japanese#5]
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-01 07:30:09

When loading AJT Japanese:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\1344485230\__init__.py", line 1, in <module>
    from . import tasks, lookup, bulk_add, gui, context_menu, editor_toolbar
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\1344485230\tasks.py", line 14, in <module>
    from .audio import format_audio_tags, AnkiAudioSourceManager
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\1344485230\audio.py", line 19, in <module>
    from .config_view import config_view as cfg
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\1344485230\config_view.py", line 11, in <module>
    from .helpers.audio_manager import AudioSourceConfig
  File "C:\Users\rider\AppData\Roaming\Anki2\addons21\1344485230\helpers\audio_manager.py", line 24, in <module>
    from .sqlite3_buddy import Sqlite3Buddy, BoundFile
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\1344485230\helpers\sqlite3_buddy.py", line 24, in <module>
    CURRENT_DB.remove_deprecated_files()
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\1344485230\helpers\sqlite_schema.py", line 33, in remove_deprecated_files
    schema = DbFileSchema(*file.name.split('.'))
TypeError: <lambda>() missing 1 required positional argument: 'ext'

**Comment by FragozoLeonardo** [comment]
confirmed.

**Comment by FragozoLeonardo** [comment]
it's working fine now, thanks!

**Comment by AommyPatty** [comment]
It works! Thank you
